packages:
  - 'apps/*'
  - 'apps/llmEnabled/*'
  - 'libs/**'
allowBuilds:
  '@google/genai': false
  '@parcel/watcher': false
  '@swc/core': true
  core-js-pure: false
  esbuild: true
  less: false
  nx: true
  protobufjs: false
  unrs-resolver: true
